### ISSUE TITLE
抢到一次算我输

### ISSUE THREAD

**Issue by rushbgg** [callmegaga/JDDuoBaoDao#1]
还不如手动抢 佛力

**Comment by rushbgg** [comment]
buy
当前价格：10
剩余抢购时间（毫秒）：741
buy
当前价格：10
剩余抢购时间（毫秒）：577
buy
当前价格：10
剩余抢购时间（毫秒）：405
buy
当前价格：10
剩余抢购时间（毫秒）：240
buy
当前价格：10
剩余抢购时间（毫秒）：67
buy
当前价格：10
剩余抢购时间（毫秒）：-117
抢购时间结束
控制台疯狂输出 其实啥都没干

**Comment by callmegaga** [comment]
应该是京东修改了出价接口，输出buy，就是在调用出价接口，但是没有调用成功的输出，我看一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rushbgg"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月5日(星期四) 下午2:15
收件人:&nbsp;"callmegaga/JDDuoBaoDao"<JDDuoBaoDao@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [callmegaga/JDDuoBaoDao] 抢到一次算我输 (#1)




buy
 当前价格：10
 剩余抢购时间（毫秒）：741
 buy
 当前价格：10
 剩余抢购时间（毫秒）：577
 buy
 当前价格：10
 剩余抢购时间（毫秒）：405
 buy
 当前价格：10
 剩余抢购时间（毫秒）：240
 buy
 当前价格：10
 剩余抢购时间（毫秒）：67
 buy
 当前价格：10
 剩余抢购时间（毫秒）：-117
 抢购时间结束
 控制台疯狂输出 其实啥都没干

**Comment by rushbgg** [comment]
😔 已经对夺宝岛失望了 同样的东西都是别人快双倍价格拍到 哎

**Comment by callmegaga** [comment]
价格没得别人高的话，那肯定抢不到，可以参考下历史价格来出价




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rushbgg"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月5日(星期四) 下午2:21
收件人:&nbsp;"callmegaga/JDDuoBaoDao"<JDDuoBaoDao@noreply.github.com&gt;;
抄送:&nbsp;"419251658"<419251658@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [callmegaga/JDDuoBaoDao] 抢到一次算我输 (#1)




😔 已经对夺宝岛失望了 同样的东西都是别人快双倍价格拍到 哎

**Comment by callmegaga** [comment]
我试了下，应该没问题了，京东把全部接口升级为了https
