### ISSUE TITLE
请问为何输入node index.js无反应？

### ISSUE THREAD

**Issue by tonymouse1997** [callmegaga/JDDuoBaoDao#13]
不好意思没有用过JavaScript，我的理解是进入server文件夹下然后输入node index.js，但是似乎cmd什么都没有干就结束了（我是在Anaconda环境下安装的nodejs）：

(base) C:\Users\Candrid\Desktop\JDDuoBaoDao-master>cd server

(base) C:\Users\Candrid\Desktop\JDDuoBaoDao-master\server>node index

(base) C:\Users\Candrid\Desktop\JDDuoBaoDao-master\server>node index.js

(base) C:\Users\Candrid\Desktop\JDDuoBaoDao-master\server>

请问是我哪里做错了吗？

**Comment by callmegaga** [comment]
修改启动方式，之前的文档写错了
