### ISSUE TITLE
pupeteer-core 招不到，这是为啥呀

### ISSUE THREAD

**Issue by charliesxia** [callmegaga/JDDuoBaoDao#15]
npm install pupeteer-core
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/pupeteer-core - Not foun

**Comment by charliesxia** [comment]
换了几个source 都没有这个库

**Comment by callmegaga** [comment]
删除目录下的node_modules和package-lock.json，再重新安装依赖试试，还不行就把npm版本降低到6.x.x试试
